### ISSUE TITLE
Call crypto.randomBytes Syncronously is bad

### ISSUE THREAD

**Issue by jtwebman** [bitbutcher/keygen#3]
Call anything like this synchronously is asking for issues. You should really make this a call back. 

https://nodejs.org/api/crypto.html#crypto_crypto_randombytes_size_callback

Blocking will mean no requests or anything else is handle for those few milliseconds or even a few seconds.

Also you should think about switching to pseudoRandomBytes as it will not error on low entropy.

**Comment by bitbutcher** [comment]
My experience of the past couple years with this module in production hasn't led me to be particularly concerned about calling crypto.randomBytes synchronously.  However, I've updated the module to be able to support asynchronous key generation for situations where synchronous calls to crypto.randomBytes are unacceptable.  The module falls back to crypto.pseudoRandomBytes if crypto.randomBytes encounters insufficient entropy.
