### ISSUE TITLE
Docs issue?

### ISSUE THREAD

**Issue by wayofthefuture** [bitbutcher/keygen#4]
The docs don't make sense:
// generate a huge url-friendly key via a custom uniqueness factor
keygen.url(11);  //-> '86ZdCFcM7TLw45rn2Hi2tN5JsKYne6Uk4XAQ76b5YWwfUtZYzfKxnv8t96u9funiTHGHzKco7JN34umyyjUvGZkBLNBQSEtj5VSkaDYXfDwQ2CmtYCmdGn6ke'

Shouldn't the length of the key be 11?

**Comment by bitbutcher** [comment]
The docs have been updated.  Thanks for the catch.  Sorry for the delay.
